name: Asset Pallet Generator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install screenshot-glb
      run: npm install --save @shopify/screenshot-glb

    - name: Take screenshots and make pallet
      run: |
        chmod +x scripts/screenshot2.sh
        ./scripts/screenshot2.sh wearables
    
    - name: Update the HTML for every wearable
      run: |
        chmod +x scripts/model-viewer8.sh
        ./scripts/model-viewer8.sh skyboxes/dam_wall_1k.hdr skyboxes/1.jpg

    - name: Update pallet site
      run: |
        chmod +x scripts/generate_html_gallery.sh
        ./scripts/generate_html_gallery.sh wearables --head --body --tail > index.html

    - name: Update README
      run: |
        python scripts/table.py wearables > README.md
        python scripts/table_html.py wearables | tee wearables/README.md wearables/index.md
      

    - name: Commit changes
      run: |
        git config --global user.name "madjin"
        git config --global user.email "32600939+madjin@users.noreply.github.com"
        git add .
        git commit -m "Update READMEs"
        git push
